name: Deploy to HubSpot

on:
  push:
    branches:
      - backup-full-version
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install HubSpot CLI
        run: |
          npm install -g @hubspot/cli@latest
          hs --version

      - name: Create HubSpot config in project root
        env:
          HUBSPOT_PAK: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
        run: |
          cat > hubspot.config.yml << 'EOFCONFIG'
          defaultPortal: RSMConsultingLLC
          portals:
            - name: RSMConsultingLLC
              portalId: 139633041
              authType: personalaccesskey
              personalAccessKey: PLACEHOLDER_TOKEN
              auth:
                tokenInfo:
                  accessToken: PLACEHOLDER_TOKEN
          EOFCONFIG

          # Replace placeholder with actual token
          sed -i "s/PLACEHOLDER_TOKEN/${HUBSPOT_PAK}/g" hubspot.config.yml

          echo "✅ Config file created in project root"
          ls -la hubspot.config.yml

      - name: Test HubSpot CLI authentication
        run: |
          echo "Testing HubSpot authentication..."
          hs accounts list

      - name: Validate project
        run: |
          echo "Validating project..."
          hs project validate
          echo "✅ Validation complete"

      - name: Upload to HubSpot
        run: |
          echo "🚀 Starting upload to HubSpot..."
          hs project upload --account=RSMConsultingLLC
          echo "✅ Upload complete"
