name: Deploy to HubSpot

on:
  push:
    branches:
      - backup-full-version
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install HubSpot CLI
        run: |
          npm install -g @hubspot/cli@latest
          hs --version

      - name: Create HubSpot config directory
        run: |
          mkdir -p ~/.config/@hubspot
          echo "Config directory created"
          ls -la ~/.config/@hubspot/

      - name: Write HubSpot config file
        env:
          HUBSPOT_PAK: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
        run: |
          cat > ~/.config/@hubspot/config.yml << 'EOFCONFIG'
          defaultPortal: RSMConsultingLLC
          portals:
            - name: RSMConsultingLLC
              portalId: 139633041
              authType: personalaccesskey
              personalAccessKey: PLACEHOLDER_TOKEN
              auth:
                tokenInfo:
                  accessToken: PLACEHOLDER_TOKEN
          EOFCONFIG

          # Replace placeholder with actual token
          sed -i "s/PLACEHOLDER_TOKEN/${HUBSPOT_PAK}/g" ~/.config/@hubspot/config.yml

          echo "Config file created successfully"
          echo "Verifying config structure (without secrets):"
          grep -v "Token\|Key" ~/.config/@hubspot/config.yml

      - name: Test HubSpot CLI authentication
        run: |
          echo "Testing HubSpot authentication..."
          hs accounts list || echo "Authentication test failed"

      - name: Validate project
        run: |
          echo "Validating project..."
          hs project validate
          echo "Validation complete"

      - name: Upload to HubSpot
        run: |
          echo "Starting upload to HubSpot..."
          hs project upload --account=RSMConsultingLLC --debug
